### ISSUE TITLE
老哥 反馈一个问题

### ISSUE THREAD

**Issue by yihanxx** [Mrzqd/Bncr_pulgins#2]
https://github.com/RedLightsDistrict/Bncr_plugins/blob/main/%E6%B6%88%E6%81%AF%E8%BD%AC%E5%8F%91.js

红灯区的消息转发插件，想把TG消息转发到频道报错

[2023-08-25T00:01:20.604] [INFO] BncrJS -  C:[\s\S]+ R:消息转发.js
TypeError: Cannot read properties of undefined (reading 'split')
    at _0x5e9e2b.reply (/bncr/BncrData/Adapter/qqPD.js:209:80)
    at _0x5e9e2b.push (/bncr/BncrData/Adapter/qqPD.js:368:31)
    at Proxy.<anonymous> (evalmachine.<anonymous>:1:3049707)
    at /bncr/BncrData/plugins/自用插件/消息转发.js:71:22
    at Array.forEach (<anonymous>)
    at /bncr/BncrData/plugins/自用插件/消息转发.js:65:20
    at new Promise (<anonymous>)
    at /bncr/BncrData/plugins/自用插件/消息转发.js:49:2
    at Object.mian (evalmachine.<anonymous>:1:3042790)
    at #run (evalmachine.<anonymous>:1:3025594)
    at new _0x4d9d6e (evalmachine.<anonymous>:1:3025123)
    at #_receive (evalmachine.<anonymous>:1:3032486)
tgBot push消息失败 TypeError: Cannot read properties of undefined (reading 'split')
    at _0x5e9e2b.reply (/bncr/BncrData/Adapter/qqPD.js:346:84)
    at _0x5e9e2b.push (/bncr/BncrData/Adapter/qqPD.js:368:31)
    at Proxy.<anonymous> (evalmachine.<anonymous>:1:3049707)
    at /bncr/BncrData/plugins/自用插件/消息转发.js:71:22
    at Array.forEach (<anonymous>)
    at /bncr/BncrData/plugins/自用插件/消息转发.js:65:20
    at new Promise (<anonymous>)
    at /bncr/BncrData/plugins/自用插件/消息转发.js:49:2
    at Object.mian (evalmachine.<anonymous>:1:3042790)
    at #run (evalmachine.<anonymous>:1:3025594)
    at new _0x4d9d6e (evalmachine.<anonymous>:1:3025123)
    at #_receive (evalmachine.<anonymous>:1:3032486)

**Comment by Mrzqd** [comment]
TG消息转发到频道要使用推送消息，适配器没写qq频道群消息推送，只写了私聊推送。（qq频道消息推送每天只能推送50条，不建议用作消息转发）。抱歉！
